# Generated by Django 3.2.25 on 2025-01-29 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_accounts', '0003_alter_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Persian', 'Teaching Persian'), ('English', 'Teaching English'), ('German', 'Teaching German'), ('Spanish', 'Teaching Spanish'), ('French', 'Teaching French'), ('Chinese', 'Teaching Chinese'), ('Italian', 'Teaching Italian'), ('Turkish', 'Teaching Turkish'), ('Swedish', 'Teaching Swedish'), ('Korean', 'Teaching Korean'), ('Russian', 'Teaching Russian'), ('Japanese', 'Teaching Japanese'), ('Ukrainian', 'Teaching Ukrainian'), ('Arabic', 'Teaching Arabic'), ('Math', 'Teaching Math'), ('Physics', 'Teaching Physics'), ('Piano', 'Teaching Piano')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True)),
                ('video_intro', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/')),
                ('cost_trial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_hourly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('course_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('language_levels', models.ManyToManyField(to='ap2_tutor.LanguageLevel')),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to='app_accounts.userprofile')),
                ('skills', models.ManyToManyField(blank=True, to='ap2_tutor.Skill')),
            ],
        ),
    ]
