# Generated by Django 3.2.25 on 2025-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
