# Generated by Django 3.2.25 on 2025-02-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0002_tutor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
