# Generated by Django 3.2.25 on 2025-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0003_alter_tutor_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageLevel',
            new_name='SkillLevel',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='language_levels',
        ),
        migrations.AddField(
            model_name='tutor',
            name='skill_level',
            field=models.ManyToManyField(to='ap2_tutor.SkillLevel'),
        ),
    ]
