# Generated by Django 3.2.25 on 2025-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0004_auto_20250625_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingcertificate',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='teachingcertificate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='applicants/certificates/%Y/%m/%d/'),
        ),
    ]
