# Generated by Django 3.2.25 on 2025-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0005_auto_20250625_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingcertificate',
            name='name',
            field=models.CharField(choices=[('', 'Select certificate'), ('toefl', 'TOEFL'), ('ielts', 'IELTS'), ('tesol', 'TESOL'), ('tefl', 'TEFL'), ('cambridge_a2', 'Cambridge English A2 Key'), ('cambridge_b1', 'Cambridge English B1 Preliminary'), ('cambridge_b2', 'Cambridge English B2 First'), ('cambridge_c1', 'Cambridge English C1 Advanced'), ('cambridge_c2', 'Cambridge English C2 Proficiency'), ('pte_academic', 'PTE Academic'), ('duolingo', 'Duolingo English Test'), ('toeic', 'TOEIC'), ('oxford', 'Oxford Test of English'), ('trinity_gese', 'Trinity College London GESE'), ('trinity_ise', 'Trinity College London ISE'), ('michigan_met', 'Michigan Tests MET'), ('michigan_ecce', 'Michigan Tests ECCE'), ('michigan_ecpe', 'Michigan Tests ECPE'), ('delf_dalf', 'DELF / DALF'), ('tcf', 'TCF'), ('tef', 'TEF'), ('dfp', 'DFP'), ('dele', 'DELE'), ('siele', 'SIELE'), ('celu', 'CELU'), ('goethe', 'Goethe-Zertifikat'), ('testdaf', 'TestDaF'), ('telc_deutsch', 'telc Deutsch'), ('dsh', 'DSH'), ('osd', 'ÖSD'), ('celi', 'CELI'), ('cils', 'CILS'), ('plida', 'PLIDA'), ('ail', 'AIL'), ('caple', 'CAPLE'), ('celpe_bras', 'CELPE-Bras'), ('torfl', 'TORFL'), ('cnavt', 'CNaVT'), ('nt2', 'NT2'), ('tisus', 'TISUS'), ('sfi', 'SFI tests'), ('yki', 'YKI'), ('norskprove', 'Norskprøve'), ('bergenstest', 'Bergenstest'), ('prove_dansk_1_2_3', 'Prøve i Dansk 1, 2, 3'), ('studieproven', 'Studieprøven'), ('islandic_test', 'Íslenskupróf fyrir útlendinga'), ('polish_certificate', 'Państwowy Egzamin Certyfikatowy z Języka Polskiego'), ('greek_certificate', 'ΚΠγ'), ('czech_cce', 'CCE'), ('czech_cce_foreigners', 'CCE – Czech for Foreigners'), ('hungarian_ecl', 'ECL Hungarian'), ('hungarian_origo', 'Origó'), ('romanian_ecl', 'ECL Romanian'), ('romanian_certificate', 'Romanian Language Proficiency Certificate'), ('bulgarian_certificate', 'Bulgarian Language Proficiency Exam'), ('other', 'Other')], max_length=100),
        ),
    ]
