# Generated by Django 3.2.25 on 2025-06-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0006_alter_teachingcertificate_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingcertificate',
            old_name='is_verified',
            new_name='is_certified',
        ),
    ]
