# Generated by Django 3.2.25 on 2025-06-28 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ap2_tutor', '0007_rename_is_verified_teachingcertificate_is_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingcertificate',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingcertificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_verifyed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
