# Generated by Django 3.2.25 on 2025-03-21 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0008_auto_20250311_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='discount',
            field=models.IntegerField(default=0, help_text='Enter a discount percentage between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
