# Generated by Django 3.2.25 on 2025-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0009_alter_providerapplication_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='reviewer_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tutor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('registered', 'Registered'), ('email_verified', 'Email Verified'), ('completed_profile', 'Completed Profile'), ('added_skills', 'Added Skills'), ('added_edu', 'Added Education'), ('decision', 'Decision'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('registered', 'Registered'), ('email_verified', 'Email Verified'), ('completed_profile', 'Completed Profile'), ('added_skills', 'Added Skills'), ('added_edu', 'Added Education'), ('decision', 'Decision'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='providerapplication',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_applicant_email'),
        ),
    ]
