# Generated by Django 3.2.25 on 2025-08-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0010_auto_20250728_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='lifetime_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('registered', 'Registered'), ('email_verified', 'Email Verified'), ('completed_profile', 'Completed Profile'), ('added_skills', 'Added Skills'), ('added_edu', 'Added Education'), ('added_availability', 'Added Availability'), ('added_pricing', 'Added Pricing'), ('decision', 'Decision'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('registered', 'Registered'), ('email_verified', 'Email Verified'), ('completed_profile', 'Completed Profile'), ('added_skills', 'Added Skills'), ('added_edu', 'Added Education'), ('added_availability', 'Added Availability'), ('added_pricing', 'Added Pricing'), ('decision', 'Decision'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
