# Generated by Django 3.2.25 on 2025-03-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0010_auto_20250321_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilllevel',
            options={'ordering': ['name']},
        ),
    ]
