# Generated by Django 3.2.25 on 2025-08-26 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0011_auto_20250826_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
