# Generated by Django 3.2.25 on 2025-08-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0012_tutor_completion_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='completion_rate',
            new_name='commission_rate',
        ),
    ]
