# Generated by Django 5.2.6 on 2025-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0013_rename_completion_rate_tutor_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('registered', 'Registered'), ('email_verified', 'Email Verified'), ('completed_profile', 'Completed Profile'), ('added_skills', 'Added Skills'), ('added_method', 'Added Method'), ('added_edu', 'Added Education'), ('added_availability', 'Added Availability'), ('added_pricing', 'Added Pricing'), ('review', 'Review'), ('decision', 'Decision'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('registered', 'Registered'), ('email_verified', 'Email Verified'), ('completed_profile', 'Completed Profile'), ('added_skills', 'Added Skills'), ('added_method', 'Added Method'), ('added_edu', 'Added Education'), ('added_availability', 'Added Availability'), ('added_pricing', 'Added Pricing'), ('review', 'Review'), ('decision', 'Decision'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
