# Generated by Django 5.2.6 on 2025-10-04 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0014_alter_providerapplication_status_alter_tutor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='public_id',
            field=models.CharField(default='666666', max_length=12),
        ),
        migrations.AddField(
            model_name='tutor',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tutor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
