# Generated by Django 5.2.6 on 2025-10-04 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0015_tutor_public_id_tutor_slug_tutor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
