# Generated by Django 5.2.6 on 2025-10-04 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0016_alter_tutor_public_id_alter_tutor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='public_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
