# Generated by Django 3.2.25 on 2025-03-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ap2_meeting', '0028_auto_20250310_2353'),
        ('ap2_tutor', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_bills', to='ap2_meeting.session')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_bills', to='ap2_tutor.tutor')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_bills', to='ap2_tutor.tutor')),
            ],
        ),
    ]
