# Generated by Django 3.2.25 on 2025-03-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_student', '0002_notification'),
        ('payments', '0003_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_bills', to='ap2_student.student'),
        ),
    ]
