# Generated by Django 3.2.25 on 2025-05-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to='app_accounts.userprofile')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
