# Generated by Django 3.2.25 on 2025-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_title', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='photos/logo/')),
                ('url', models.URLField(blank=True, max_length=100)),
                ('phone_1', models.CharField(blank=True, max_length=50)),
                ('phone_2', models.CharField(blank=True, max_length=50)),
                ('email_1', models.CharField(blank=True, max_length=50)),
                ('email_2', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=150)),
                ('address_line_2', models.CharField(blank=True, max_length=150)),
                ('site_description_1', models.CharField(blank=True, max_length=300)),
                ('site_description_2', models.CharField(blank=True, max_length=300)),
                ('site_slogan_1', models.CharField(blank=True, max_length=300)),
                ('site_slogan_2', models.CharField(blank=True, max_length=300)),
                ('text_1', models.CharField(blank=True, max_length=500)),
                ('text_2', models.CharField(blank=True, max_length=500)),
                ('text_3', models.CharField(blank=True, max_length=500)),
                ('text_4', models.CharField(blank=True, max_length=500)),
                ('text_5', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
