# Generated by Django 3.2.25 on 2025-03-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
