# Generated by Django 3.2.25 on 2025-03-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0004_cfboolean_cfdatetime_cfdecimal_cffile_cfimage_cftext_cfurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFInteger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
