# Generated by Django 3.2.25 on 2025-03-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0006_cfchar_cfemail_cffloat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CFBoolean',
        ),
        migrations.DeleteModel(
            name='CFChar',
        ),
        migrations.DeleteModel(
            name='CFDateTime',
        ),
        migrations.DeleteModel(
            name='CFDecimal',
        ),
        migrations.DeleteModel(
            name='CFEmail',
        ),
        migrations.DeleteModel(
            name='CFFile',
        ),
        migrations.DeleteModel(
            name='CFFloat',
        ),
        migrations.DeleteModel(
            name='CFImage',
        ),
        migrations.DeleteModel(
            name='CFInteger',
        ),
        migrations.DeleteModel(
            name='CFText',
        ),
        migrations.DeleteModel(
            name='CFURL',
        ),
    ]
