# Generated by Django 3.2.25 on 2025-03-22 13:57

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0007_auto_20250321_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title (e.g., Home, About Us)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Unique URL identifier (e.g., home, about-us)', max_length=100, unique=True)),
                ('content', django_quill.fields.QuillField(help_text='Rich-text content for this page')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this page was last updated')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
