# Generated by Django 3.2.25 on 2025-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0008_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.RemoveField(
            model_name='page',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('terms', 'Terms and Conditions'), ('contact', 'Contact Us')], default='home', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(),
        ),
    ]
