# Generated by Django 3.2.25 on 2025-03-22 15:13

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0009_auto_20250322_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
