# Generated by Django 3.2.25 on 2025-03-22 15:31

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0010_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message2',
            field=django_quill.fields.QuillField(blank=True, help_text='Rich-text field for message2'),
        ),
    ]
