# Generated by Django 3.2.25 on 2025-03-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0011_contactus_message2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='message2',
        ),
    ]
