# Generated by Django 3.2.25 on 2025-07-21 12:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0013_articlefeedback_helparticle_helpcategory_helpsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='helparticle',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='_app_pages_helparticle_related_articles_+', to='app_pages.HelpArticle'),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articlefeedback',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app_pages.helparticle'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
