# Generated by Django 3.2.25 on 2025-07-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0014_auto_20250721_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpsection',
            options={'ordering': ['category__order', 'order']},
        ),
    ]
