# Generated by Django 5.2.6 on 2025-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0015_alter_helpsection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helparticle',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='app_pages.helparticle'),
        ),
    ]
