# Generated by Django 5.2.6 on 2025-10-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcardpage',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='total_qr_scans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location_data', models.JSONField(blank=True, null=True)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='vcard.vcardpage')),
            ],
            options={
                'indexes': [models.Index(fields=['vcard', 'scanned_at'], name='vcard_qrcod_vcard_i_3c8159_idx')],
            },
        ),
        migrations.CreateModel(
            name='VCardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('qr_scan', 'QR Scan'), ('phone_click', 'Phone Click'), ('email_click', 'Email Click'), ('website_click', 'Website Click'), ('social_click', 'Social Media Click')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('vcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='vcard.vcardpage')),
            ],
            options={
                'verbose_name_plural': 'VCard Analytics',
                'indexes': [models.Index(fields=['vcard', 'timestamp'], name='vcard_vcard_vcard_i_3f973b_idx'), models.Index(fields=['event_type', 'timestamp'], name='vcard_vcard_event_t_70a6b6_idx')],
            },
        ),
    ]
