# Generated by Django 5.2.6 on 2025-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0002_vcardpage_facebook_vcardpage_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcardpage',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vcard/backgrounds/'),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vcard/logos/'),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='primary_color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='secondary_color',
            field=models.CharField(default='#1e40af', max_length=7),
        ),
    ]
