# Generated by Django 5.2.6 on 2025-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0004_vcardpage_address_vcardpage_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcardpage',
            name='qr_background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='qr_foreground_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='qr_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vcard/qr_logos/'),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='qr_logo_size',
            field=models.PositiveIntegerField(default=80, help_text='Logo size in percentage (20-100)'),
        ),
        migrations.AddField(
            model_name='vcardpage',
            name='qr_style',
            field=models.CharField(choices=[('square', 'Square Dots'), ('rounded', 'Rounded Dots'), ('circle', 'Circular Dots'), ('diamond', 'Diamond Dots')], default='square', max_length=20),
        ),
        migrations.DeleteModel(
            name='VCardPage1',
        ),
    ]
