# Generated by Django 3.2.25 on 2025-01-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_accounts', '0003_alter_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('session_count', models.IntegerField(default=0)),
                ('tutor_count', models.IntegerField(default=0)),
                ('interests', models.ManyToManyField(blank=True, to='ap2_student.Subject')),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='app_accounts.userprofile')),
            ],
        ),
    ]
