# Generated by Django 3.2.25 on 2025-03-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0011_alter_skilllevel_options'),
        ('ap2_student', '0004_auto_20250311_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='ap2_student.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='ap2_tutor.tutor')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('student', 'tutor')},
            },
        ),
    ]
