# Generated by Django 3.2.25 on 2025-03-22 00:05

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_content_filler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFRichText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', django_quill.fields.QuillField(blank=True, null=True)),
            ],
        ),
    ]
