# Generated by Django 3.2.25 on 2025-05-19 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userspecialization',
            old_name='doc',
            new_name='certificate',
        ),
        migrations.AlterField(
            model_name='userskill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('need_interview', 'Need Interview'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifyed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
