# Generated by Django 3.2.25 on 2025-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_auto_20250520_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
