# Generated by Django 3.2.25 on 2025-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0007_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('', 'Select a language'), ('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Chinese', 'Chinese (Simplified)'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Arabic', 'Arabic'), ('Hindi', 'Hindi'), ('Bengali', 'Bengali'), ('Turkish', 'Turkish'), ('Dutch', 'Dutch'), ('Polish', 'Polish'), ('Ukrainian', 'Ukrainian'), ('Vietnamese', 'Vietnamese'), ('Thai', 'Thai'), ('Persian', 'Persian (Farsi)'), ('Swedish', 'Swedish'), ('Finnish', 'Finnish'), ('Norwegian', 'Norwegian'), ('Danish', 'Danish'), ('Greek', 'Greek'), ('Hebrew', 'Hebrew'), ('Indonesian', 'Indonesian'), ('Malay', 'Malay'), ('Romanian', 'Romanian'), ('Czech', 'Czech'), ('Hungarian', 'Hungarian')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('', 'Select your preferred language'), ('English', 'English'), ('Chinese', 'Chinese (Simplified)'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Arabic', 'Arabic'), ('Bengali', 'Bengali'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Indonesian', 'Indonesian'), ('Urdu', 'Urdu'), ('German', 'German'), ('Japanese', 'Japanese'), ('Swahili', 'Swahili'), ('Marathi', 'Marathi'), ('Telugu', 'Telugu'), ('Turkish', 'Turkish'), ('Tamil', 'Tamil'), ('Korean', 'Korean'), ('Vietnamese', 'Vietnamese'), ('Italian', 'Italian'), ('Dutch', 'Dutch'), ('Polish', 'Polish'), ('Ukrainian', 'Ukrainian'), ('Romanian', 'Romanian'), ('Greek', 'Greek'), ('Czech', 'Czech'), ('Swedish', 'Swedish'), ('Hungarian', 'Hungarian'), ('Danish', 'Danish'), ('Finnish', 'Finnish'), ('Norwegian', 'Norwegian'), ('Persian', 'Persian (Farsi)'), ('Thai', 'Thai'), ('Hebrew', 'Hebrew'), ('Malay', 'Malay'), ('Filipino', 'Filipino'), ('Punjabi', 'Punjabi'), ('Burmese', 'Burmese'), ('Khmer', 'Khmer'), ('Lao', 'Lao'), ('Nepali', 'Nepali'), ('Sinhala', 'Sinhala'), ('Kazakh', 'Kazakh'), ('Uzbek', 'Uzbek'), ('Azerbaijani', 'Azerbaijani'), ('Armenian', 'Armenian'), ('Georgian', 'Georgian'), ('Yoruba', 'Yoruba'), ('Igbo', 'Igbo'), ('Hausa', 'Hausa'), ('Amharic', 'Amharic'), ('Zulu', 'Zulu'), ('Xhosa', 'Xhosa'), ('Afrikaans', 'Afrikaans'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry')], max_length=20, unique=True),
        ),
    ]
