# Generated by Django 3.2.25 on 2025-06-20 23:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_accounts', '0008_auto_20250525_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(help_text='For sorting purposes')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='userskill',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_verifyed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('graduation_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('document', models.FileField(blank=True, null=True, upload_to='applicants/education/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg'])])),
                ('description', models.TextField(blank=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('need_interview', 'Need Interview'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('needs_interview', models.BooleanField(default=False)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_accounts.degreelevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu_verifyed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education Record',
                'verbose_name_plural': 'Education Records',
                'ordering': ['-graduation_year'],
            },
        ),
    ]
