# Generated by Django 3.2.25 on 2025-06-21 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0009_auto_20250621_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='graduation_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
