# Generated by Django 3.2.25 on 2025-06-24 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0010_auto_20250622_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreelevel',
            name='name',
            field=models.CharField(choices=[('', 'Select degree'), ('high_school', 'High School Diploma'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('professional', 'Professional Degree'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='graduation_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
