# Generated by Django 3.2.25 on 2025-06-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0011_auto_20250625_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usereducation',
            options={'ordering': ['-end_year'], 'verbose_name': 'Education Record', 'verbose_name_plural': 'Education Records'},
        ),
        migrations.RenameField(
            model_name='usereducation',
            old_name='graduation_year',
            new_name='end_year',
        ),
    ]
