# Generated by Django 3.2.25 on 2025-06-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0013_auto_20250627_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('trans', 'Transgendered'), ('ambiguous', 'Ambiguous'), ('neuter', 'Neuter')], default='male', max_length=20, null=True),
        ),
    ]
