# Generated by Django 3.2.25 on 2025-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0015_auto_20250628_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
