# Generated by Django 3.2.25 on 2025-07-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0016_auto_20250706_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_agreed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
