# Generated by Django 3.2.25 on 2025-07-09 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_accounts', '0017_userprofile_terms_agreed_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('nda', 'Instructor NDA')], max_length=20)),
                ('consent_version', models.CharField(help_text='Version ID of legal document (e.g. v1.2)', max_length=20)),
                ('agreed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent Log',
                'verbose_name_plural': 'User Consent Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginIPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_new_ip', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False, help_text='Manually or automatically flagged as suspicious')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loginIPLogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login IP Log',
                'verbose_name_plural': 'Login IP Logs',
                'ordering': ['-login_time'],
            },
        ),
    ]
