# Generated by Django 3.2.25 on 2025-07-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0018_loginiplog_userconsentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='terms_agreed_ip',
        ),
    ]
