# Generated by Django 3.2.25 on 2025-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0019_remove_userprofile_terms_agreed_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pss_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
