# Generated by Django 3.2.25 on 2025-08-02 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0026_alter_userskill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='applicants/skills/thumbnail/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='video',
            field=models.FileField(null=True, upload_to='applicants/skills/video/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'ts'])]),
        ),
    ]
