# Generated by Django 3.2.25 on 2025-08-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0027_auto_20250802_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='offers_in_person',
            field=models.BooleanField(default=False),
        ),
    ]
