# Generated by Django 3.2.25 on 2025-08-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0028_auto_20250812_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teaching_radius',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Maximum distance you'll travel (in km/miles)", null=True),
        ),
    ]
