# Generated by Django 3.2.25 on 2025-08-11 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0029_userprofile_teaching_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Primary city for in-person classes', max_length=100, verbose_name='in-person class location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='offers_in_person',
            field=models.BooleanField(default=False, help_text='This user is available for face-to-face sessions', verbose_name='Offers in-person classes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_radius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How far the user will travel for sessions (0-100 km)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum travel distance (km)'),
        ),
    ]
