# Generated by Django 3.2.25 on 2025-08-12 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0031_auto_20250812_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meeting_preference',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('my_location', 'My location'), ('formal_institution', 'Formal institution'), ('public', 'Public')], default='any', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_radius',
            field=models.PositiveSmallIntegerField(blank=True, default=10, help_text='How far the user will travel for sessions (0-100 km)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum travel distance (km)'),
        ),
    ]
