# Generated by Django 3.2.25 on 2025-08-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0032_auto_20250812_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='teaching_radius',
            new_name='meeting_radius',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='meeting_preference',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='offers_in_person',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meeting_location',
            field=models.CharField(blank=True, choices=[('any', 'Any suitable location in my area'), ('my_location', 'Only at my specified location'), ('formal_institution', 'Educational institutions (schools, universities)'), ('public', 'Public spaces (cafés, libraries, co-working spaces)')], default='any', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meeting_method',
            field=models.CharField(choices=[('online', 'Online Only'), ('hybrid', 'Online + In-Person'), ('in_person', 'In-Person Only')], default='online', max_length=10, verbose_name='Meeting Method'),
        ),
    ]
