# Generated by Django 3.2.25 on 2025-08-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0033_auto_20250813_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Primary city area for in-person classes', max_length=100, verbose_name='city area'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_type'], name='app_account_user_ty_100cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['meeting_method'], name='app_account_meeting_d06841_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='app_account_latitud_43032a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['city', 'country'], name='app_account_city_a36b11_idx'),
        ),
    ]
