# Generated by Django 3.2.25 on 2025-08-17 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0034_auto_20250814_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inp_aim',
            field=models.CharField(blank=True, choices=[('english_for_business', 'English for business'), ('daily_conversation', 'Daily Conversation'), ('free_discussion', 'Free Discussion'), ('formal_exams', 'Educational Exams (schools, universities)'), ('formal_tests', 'Formal Tests (TOEFL, IELTS, ...)'), ('networking', 'Netwirking (Find new language partners)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inp_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
