# Generated by Django 3.2.25 on 2025-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0035_auto_20250818_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='inp_aim',
            field=models.CharField(blank=True, choices=[('english_for_business', 'English for business'), ('daily_conversation', 'Daily Conversation'), ('free_discussion', 'Free Discussion'), ('formal_exams', 'Educational Exams (schools, universities)'), ('formal_tests', 'Formal Tests (TOEFL, IELTS, ...)'), ('networking', 'Networking (Find new language partners)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inp_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
