# Generated by Django 3.2.25 on 2025-01-29 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Persian', 'Teaching Persian'), ('English', 'Teaching English'), ('German', 'Teaching German'), ('Spanish', 'Teaching Spanish'), ('French', 'Teaching French'), ('Chinese', 'Teaching Chinese'), ('Italian', 'Teaching Italian'), ('Turkish', 'Teaching Turkish'), ('Swedish', 'Teaching Swedish'), ('Korean', 'Teaching Korean'), ('Russian', 'Teaching Russian'), ('Japanese', 'Teaching Japanese'), ('Ukrainian', 'Teaching Ukrainian'), ('Arabic', 'Teaching Arabic'), ('Math', 'Teaching Math'), ('Physics', 'Teaching Physics'), ('Piano', 'Teaching Piano')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True)),
                ('video_intro', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/')),
                ('cost_trial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_hourly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('course_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('language_levels', models.ManyToManyField(to='app_temp.LanguageLevel2')),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor2_profile', to='app_accounts.userprofile')),
                ('skills', models.ManyToManyField(blank=True, to='app_temp.Skill2')),
            ],
        ),
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('session_count', models.IntegerField(default=0)),
                ('tutor_count', models.IntegerField(default=0)),
                ('interests', models.ManyToManyField(blank=True, to='app_temp.Subject2')),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student2_profile', to='app_accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_session', models.DateTimeField(default=datetime.datetime.now)),
                ('end_session', models.DateTimeField(default=datetime.datetime.now)),
                ('student', models.ManyToManyField(blank=True, related_name='schedules2', to='app_temp.Student2')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules2', to='app_temp.tutor2')),
            ],
        ),
    ]
