# Generated by Django 3.2.25 on 2025-01-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_alter_userprofile_last_modified'),
        ('app_temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('session_count', models.IntegerField(default=0)),
                ('tutor_count', models.IntegerField(default=0)),
                ('interests', models.ManyToManyField(blank=True, to='app_temp.Subject2')),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student3_profile', to='app_accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor3_profile', to='app_accounts.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='student2',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='student2',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tutor2',
            name='language_levels',
        ),
        migrations.RemoveField(
            model_name='tutor2',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tutor2',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Schedule2',
        ),
        migrations.DeleteModel(
            name='Student2',
        ),
        migrations.DeleteModel(
            name='Tutor2',
        ),
        migrations.AddField(
            model_name='session3',
            name='students',
            field=models.ManyToManyField(to='app_temp.Student3'),
        ),
        migrations.AddField(
            model_name='session3',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_temp.tutor3'),
        ),
    ]
