# Generated by Django 3.2.25 on 2025-01-29 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ap2_student', '0001_initial'),
        ('ap2_tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('till_now', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('start_session', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_session', models.DateTimeField(default=django.utils.timezone.now)),
                ('students', models.ManyToManyField(related_name='schedules', to='ap2_student.Student')),
                ('tutor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ap2_tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('0', '0')])),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='ap2_student.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='ap2_tutor.tutor')),
            ],
        ),
    ]
