# Generated by Django 3.2.25 on 2025-01-29 09:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0001_initial'),
        ('ap2_student', '0001_initial'),
        ('ap2_meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=10)),
                ('start_session', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_session', models.DateTimeField(default=django.utils.timezone.now)),
                ('students', models.ManyToManyField(related_name='schedules', to='ap2_student.Student')),
                ('tutor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ap2_tutor.tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
