# Generated by Django 3.2.25 on 2025-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_student', '0001_initial'),
        ('ap2_meeting', '0002_auto_20250129_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(related_name='sessions', to='ap2_student.Student'),
        ),
    ]
