# Generated by Django 3.2.25 on 2025-08-21 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ap2_meeting', '0002_alter_appointmentsetting_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=10)),
                ('start_time_utc', models.TimeField()),
                ('end_time_utc', models.TimeField()),
                ('status', models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('reserving', 'Reserving')], default='free', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
