# Generated by Django 5.2.6 on 2025-09-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0003_availablerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablerule',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
    ]
