# Generated by Django 3.2.25 on 2025-02-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0005_auto_20250131_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('partially_attended', 'Partially Attended')], default='pending', max_length=20),
        ),
    ]
