# Generated by Django 3.2.25 on 2025-02-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0006_auto_20250202_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='timezone',
            new_name='tutor_timezone',
        ),
        migrations.AddField(
            model_name='session',
            name='tutor_timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='user_timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
