# Generated by Django 3.2.25 on 2025-02-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0007_auto_20250202_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_timezone',
            new_name='students_timezone',
        ),
    ]
