# Generated by Django 3.2.25 on 2025-02-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0008_rename_user_timezone_session_students_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='end_time',
            new_name='end_time_utc',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='start_time',
            new_name='start_time_utc',
        ),
    ]
