# Generated by Django 3.2.25 on 2025-02-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0011_alter_availability_tutor_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('reserved', 'Reserved'), ('reserving', 'Reserving')], default='free', max_length=20),
        ),
    ]
