# Generated by Django 3.2.25 on 2025-02-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0012_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('reserving', 'Reserving')], default='free', max_length=20),
        ),
    ]
