# Generated by Django 3.2.25 on 2025-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0014_auto_20250216_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.AlterField(
            model_name='appointmentsettings',
            name='session_length',
            field=models.CharField(choices=[('1', '30 min'), ('2', '1 Hour'), ('3', '90 min'), ('4', '2 Hours'), ('6', '3 Hours')], default='2', max_length=10),
        ),
    ]
