# Generated by Django 3.2.25 on 2025-02-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0018_alter_appointmentsetting_session_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsetting',
            name='session_length',
            field=models.CharField(choices=[('1', '30 min'), ('2', '1 Hour'), ('3', '90 min'), ('4', '2 Hours'), ('6', '3 Hours')], default='2', max_length=10),
        ),
    ]
