# Generated by Django 3.2.25 on 2025-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0020_alter_appointmentsetting_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1, null=True),
        ),
    ]
