# Generated by Django 3.2.25 on 2025-02-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_student', '0001_initial'),
        ('ap2_meeting', '0021_session_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ap2_meeting.session'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('published', 'Published')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('student', 'session')},
        ),
    ]
