# Generated by Django 3.2.25 on 2025-02-25 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0022_auto_20250225_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='session',
            field=models.ForeignKey(blank=True, limit_choices_to={'student': django.db.models.expressions.F('student'), 'tutor': django.db.models.expressions.F('tutor')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ap2_meeting.session'),
        ),
    ]
