# Generated by Django 3.2.25 on 2025-02-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0023_alter_review_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ap2_meeting.session'),
        ),
    ]
