# Generated by Django 3.2.25 on 2025-02-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0003_alter_tutor_rating'),
        ('ap2_student', '0001_initial'),
        ('ap2_meeting', '0026_auto_20250225_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ap2_student.student'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ap2_tutor.tutor'),
        ),
    ]
