# Generated by Django 3.2.25 on 2025-03-10 20:23

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0027_auto_20250226_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='appointment_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=6, max_length=10, prefix=''),
        ),
        migrations.AddField(
            model_name='session',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('trial', 'Trial')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('partially_attended', 'Partially Attended')], default='pending', max_length=20),
        ),
    ]
