# Generated by Django 3.2.25 on 2025-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_meeting', '0031_auto_20250324_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews_sessions', to='ap2_meeting.Review'),
        ),
    ]
