# Generated by Django 3.2.25 on 2025-04-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap2_tutor', '0011_alter_skilllevel_options'),
        ('ap2_meeting', '0033_auto_20250410_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsetting',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_settings', to='ap2_tutor.tutor'),
        ),
    ]
