# Generated by Django 3.2.25 on 2025-08-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_in_person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpersonrequest',
            name='session_duration_hours',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=4, verbose_name='duration'),
        ),
    ]
