# Generated by Django 3.2.25 on 2025-08-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_in_person', '0002_alter_inpersonrequest_session_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersonrequest',
            name='current_level',
            field=models.TextField(blank=True, choices=[('a1', 'A1 (Beginner)'), ('a2', 'A2 (Elementary)'), ('b1', 'B1 (Intermediate)'), ('b2', 'B2 (Upper-Intermediate)'), ('c1', 'C1 (Advanced)'), ('c2', 'C2 (Proficient)'), ('native', 'Native (Fluent as a first language)')], help_text='Student current level'),
        ),
    ]
